### ISSUE TITLE
2D array not being plotted properly as a heatmap-like

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/GeoData.jl#103] opened 2020-11-15 19:24 UTC
I expected the following 2D `GeoArray` to be plotted using `heatmap` or `contour`, but it's plotted as a bunch of lines. Is this expected behavior? If not, I'm happy to try and fix the plotting recipe.

![image](https://user-images.githubusercontent.com/20099589/99194510-c241f680-274d-11eb-9be2-288d70e5696b.png)

**Comment by rafaqz** [comment] 2020-11-16 00:45
GeoData plotting is from before there were abstract type hierarchy for dims. So it dispatches on `Lat` and `Lon` which are concrete types.

I'm not sure of the best way to do this.  There are 3 options:

1. We could add abstract lat/lon type to dispatch on:

```julia
abstract type LatDim <: YDim end
abstract type LonDim <: XDim end
@dim Lon LonDim "Longitude"
@dim Lat LatDim "Longitude"
```

in GeoData `dimensions.jl`. You would inherit from them in your `@dim` macro. Then the recipes in the GeoData `plotrecipes,jl` would have to be updated to dispatch on `LatDim` and `LonDim`.

2. GeoArray could modify the plotting behavior of all `XDim` and `YDim` to be heatmaps. But that might be confusing.

3. Define a `Heatmap` trait in DimensionalData and make heatmaps whenever there are two dims with the trait - tiled if there are additional dims. 

I would try the first option first.

**Comment by ali-ramadhan** [comment] 2020-11-23 22:43
Hmmm, seems like there are almost two different kinds of geo plots: `LatLonGeoPlot` and `XYZGeoPlot`?

Does it maybe make sense to have different plotting recipes for the two?

Not sure if this is essentially option 1, are there any disadvantages to subtyping

```julia
abstract type LatDim <: YDim end
abstract type LonDim <: XDim end
```
?

**Comment by rafaqz** [comment] 2020-11-24 03:16
Yeah that's option 1. No disadvantages, that's the current behavior - we are just inserting a abstract types in between `Lat` and `YDim` so we can use it to get the same behavior with other dim types.

If there are two types, how would an XYX plot be different to the current LatLon plot? (i.e. tiled heatmaps)

If they are the same, it might make more sense to use:

```julia
abstract type GeoYDim <: YDim end
abstract type GeoXDim <: XDim end
@dim Lon GeoXDim "Longitude"
@dim Lat GeoYDim "Latitude"
```

The problem is differentiating from default DimensionalData plots, which wont plot a heat map unless you actually use `heatmap`. My guess is that mostly people don't want a heatmap by default except for raster data.

**Comment by ali-ramadhan** [comment] 2020-11-25 01:09
That sounds like a good approach! Will try playing around with an implementation and open a PR.

**Comment by rafaqz** [comment] 2021-02-09 01:42
This is merged now

**Closed by rafaqz** 2021-02-09 01:42 UTC
